### ISSUE TITLE
Bash script files have CRLF line endings

### ISSUE THREAD

**Issue by poussa** [JoshHilliker/Telemetry-Infra#1]
All the .sh files in top directory have CRLF line endings (DOS/Windows). Then you try to execute them on Linux (Centos 8 in my case) , you get:

```
$ ./grafana.sh
-bash: ./grafana.sh: /bin/bash^M: bad interpreter: No such file or directory
$ file grafana.sh
grafana.sh: Bourne-Again shell script, ASCII text executable, with CRLF line terminators
```

I can send a patch to fix this unless there is a reason why it is this way.

**Comment by poussa** [comment]
Also, the collectd.conf has the issue and collectd can not consume it.

**Comment by poussa** [comment]
Also, the collectd.conf has syntax error (and CRLF) which is why it is failing to load (<Plugin memory> is missing the closing directive).

https://github.com/JoshHilliker/Telemetry-Infra/blob/c198c9d4c616f8633c77d9aebecf9bfe1d0e7fce/collectd.conf#L241

**Comment by poussa** [comment]
Also, the prometheus.conf has the same (CRLF) issue and prometheus can not consume it.

**Comment by JoshHilliker** [comment]
Fixed grafana.sh -  sublime put in windows returns, I've fixed my sublime to use unix returns.

**Comment by JoshHilliker** [comment]
Updated collectd.conf, FYI: this file requires customization based on the environment & what specific plugins you want to activate.

**Comment by JoshHilliker** [comment]
Same with Prometheus.service file.  I will also validate on collectd_exporter.service.
